name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set your Python version here
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb  # Install Xvfb
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests with Xvfb
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &  # Start Xvfb
        DISPLAY=:99.0  # Use the virtual display
        python -m unittest discover -s . -p "test_*.py"
